frontend:
    image: node:7
    volumes:
        - ./frontend:/src
        - ./static:/static
        - ./node_modules:/src/node_modules
    working_dir: /src
    command: make build
server:
    build: server
    volumes:
        - ./static:/srv
    ports:
        - 0.0.0.0:8080:80
