frontend:
    image: node:7
    volumes:
        - ./frontend:/src
        - ./static:/static
        - /src/node_modules
    working_dir: /src
    command: make watch
server:
    image: webratio/nodejs-http-server:0.9.0
    volumes:
        - ./static:/opt/www
    ports:
        - 0.0.0.0:8080:8080
